#
# Make Xinu's C run-time support library
#

# Name of this library
LIBNAME := libxc

# C files to compile (.c)
CFILES  := doprnt.c 

# Assembly files to compile (.S)
SFILES  :=

# Directory in which to place the output library, and
# location of common Makerules
LIBDIR  := ..

include $(LIBDIR)/Makerules
